import type { FlywayId } from "./types";

export const FLYWAY_OPTIONS: { id: FlywayId; label: string }[] = [
  { id: "pacific", label: "Pacific" },
  { id: "central", label: "Central" },
  { id: "mississippi", label: "Mississippi" },
  { id: "atlantic", label: "Atlantic" },
];

export const STATES_BY_FLYWAY: Record<FlywayId, { code: string; name: string }[]> = {
  pacific: [
    { code: "AK", name: "Alaska" },
    { code: "WA", name: "Washington" },
    { code: "OR", name: "Oregon" },
    { code: "CA", name: "California" },
    { code: "ID", name: "Idaho" },
    { code: "NV", name: "Nevada" },
    { code: "UT", name: "Utah" },
    { code: "AZ", name: "Arizona" },
  ],
  central: [
    { code: "MT", name: "Montana" },
    { code: "WY", name: "Wyoming" },
    { code: "CO", name: "Colorado" },
    { code: "NM", name: "New Mexico" },
    { code: "ND", name: "North Dakota" },
    { code: "SD", name: "South Dakota" },
    { code: "NE", name: "Nebraska" },
    { code: "KS", name: "Kansas" },
    { code: "OK", name: "Oklahoma" },
    { code: "TX", name: "Texas" },
  ],
  mississippi: [
    { code: "MN", name: "Minnesota" },
    { code: "WI", name: "Wisconsin" },
    { code: "IA", name: "Iowa" },
    { code: "MO", name: "Missouri" },
    { code: "AR", name: "Arkansas" },
    { code: "LA", name: "Louisiana" },
    { code: "MS", name: "Mississippi" },
    { code: "AL", name: "Alabama" },
    { code: "IL", name: "Illinois" },
    { code: "IN", name: "Indiana" },
    { code: "KY", name: "Kentucky" },
    { code: "TN", name: "Tennessee" },
    { code: "MI", name: "Michigan" },
    { code: "OH", name: "Ohio" },
  ],
  atlantic: [
    { code: "ME", name: "Maine" },
    { code: "NH", name: "New Hampshire" },
    { code: "VT", name: "Vermont" },
    { code: "MA", name: "Massachusetts" },
    { code: "NY", name: "New York" },
    { code: "NJ", name: "New Jersey" },
    { code: "PA", name: "Pennsylvania" },
    { code: "DE", name: "Delaware" },
    { code: "MD", name: "Maryland" },
    { code: "VA", name: "Virginia" },
    { code: "NC", name: "North Carolina" },
    { code: "SC", name: "South Carolina" },
    { code: "GA", name: "Georgia" },
    { code: "FL", name: "Florida" },
    { code: "WV", name: "West Virginia" },
  ],
};

export const CITIES_BY_STATE: Record<string, string[]> = {
  AK: ["Palmer", "Anchorage", "Juneau", "Fairbanks"],
  WA: ["Puget Sound", "Othello", "Skagit", "Tri-Cities"],
  OR: ["Klamath Falls", "Columbia River", "Summer Lake", "Malheur"],
  CA: ["Sacramento", "Los Banos", "Suisun", "Salton Sea"],
  ID: ["Caldwell", "American Falls", "Sandpoint"],
  NV: ["Fallon", "Ruby Valley", "Pahranagat"],
  UT: ["Great Salt Lake", "Delta", "Bear River"],
  AZ: ["Willcox", "Cibola", "Mesa"],
  MT: ["Bowdoin", "Freezout", "Billings"],
  WY: ["Seedskadee", "Casper", "Jackson"],
  CO: ["Denver", "Pueblo", "Sterling", "Fort Morgan", "Alamosa", "Lamar"],
  NM: ["Bosque del Apache", "Las Vegas", "Clayton"],
  ND: ["Bismarck", "Minot", "Devils Lake", "Fargo"],
  SD: ["Pierre", "Aberdeen", "Sand Lake", "Chamberlain"],
  NE: ["North Platte", "Valentine", "Kearney", "Rainwater Basin"],
  KS: ["Cheyenne Bottoms", "Quivira", "Wichita"],
  OK: ["Washita", "Kaw Lake", "Enid"],
  TX: ["Amarillo", "Lubbock", "Midland", "Anahuac", "Port Arthur"],
  MN: ["Minneapolis", "Thief River Falls", "Agassiz", "Albert Lea"],
  WI: ["Horicon", "Green Bay", "La Crosse"],
  IA: ["Des Moines", "Forney Lake", "Keokuk"],
  MO: ["Loess Bluffs", "St. Louis", "Duck Creek"],
  AR: ["Stuttgart", "St. Charles", "Bayou Meto"],
  LA: ["Lafayette", "Monroe", "Gueydan", "Sabine"],
  MS: ["Moon Lake", "Yazoo", "Jackson"],
  AL: ["Wheeler", "Mobile", "Eufaula"],
  IL: ["Rend Lake", "Carlyle", "Union County"],
  IN: ["Hovey Lake", "Patoka", "Kankakee"],
  KY: ["Ballard", "Kentucky Lake", "Sloughs"],
  TN: ["Reelfoot", "Tennessee NWR", "Memphis"],
  MI: ["Saginaw Bay", "Shiawassee", "Muskegon"],
  OH: ["Ottawa", "Mosquito Creek", "Pymatuning"],
  ME: ["Merrymeeting Bay", "Sebago", "Moosehorn"],
  NH: ["Great Bay", "Umbagog"],
  VT: ["Lake Champlain", "Missisquoi"],
  MA: ["Plum Island", "Cape Cod"],
  NY: ["Montezuma", "Long Island", "Iroquois"],
  NJ: ["Forsythe", "Delaware Bay", "Barnegat"],
  PA: ["Pymatuning", "Middle Creek", "Erie"],
  DE: ["Bombay Hook", "Prime Hook"],
  MD: ["Chesapeake Bay", "Eastern Shore", "Blackwater"],
  VA: ["Back Bay", "Chincoteague", "Presquile"],
  NC: ["Mattamuskeet", "Currituck", "Pungo"],
  SC: ["Santee", "ACE Basin", "Savannah"],
  GA: ["Savannah NWR", "Okefenokee", "Lake Seminole"],
  FL: ["Lake Okeechobee", "Tampa Bay", "St. Johns"],
  WV: ["McClintic", "Bluestone"],
};

export const REPORT_SPECIES = [
  "Mallard",
  "Gadwall",
  "Wigeon",
  "Pintail",
  "Shoveler",
  "Blue-winged teal",
  "Green-winged teal",
  "Canvasback",
  "Redhead",
  "Scaup",
  "Canada goose",
  "Snow goose",
  "White-front",
  "Mixed bag",
  "Other",
] as const;

export function stateName(code: string): string {
  for (const list of Object.values(STATES_BY_FLYWAY)) {
    const hit = list.find((s) => s.code === code);
    if (hit) return hit.name;
  }
  return code;
}
